name = "ytm-stream-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# If deploying to Cloudflare with KV, uncomment and bind your KV namespace:
# [[kv_namespaces]]
# binding = "MUSIC_CACHE"
# id = "your-kv-namespace-id"

[[kv_namespaces]]
binding = "MUSIC_CACHE"
id = "5c8108d17d2148a3afb17cb428042b67"